# Generated by Django 5.0.3 on 2024-04-30 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KVStore",
            fields=[
                ("kv_id", models.AutoField(primary_key=True, serialize=False)),
                ("fk_id", models.IntegerField()),
                ("key", models.TextField()),
                ("value", models.TextField()),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[("string", "String"), ("number", "Number")],
                        max_length=10,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LibraryCollection",
            fields=[
                (
                    "collection_name",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Modes",
            fields=[
                ("mode_id", models.AutoField(primary_key=True, serialize=False)),
                ("mode_name", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Readers",
            fields=[
                ("reader_id", models.AutoField(primary_key=True, serialize=False)),
                ("reader_name", models.TextField()),
                ("reader_kwargs", models.ManyToManyField(to="config_library.kvstore")),
            ],
        ),
        migrations.CreateModel(
            name="LoggerConfiguration",
            fields=[
                ("logger_id", models.AutoField(primary_key=True, serialize=False)),
                ("logger_name", models.TextField()),
                (
                    "collection_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="config_library.librarycollection",
                    ),
                ),
                (
                    "readers",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="config_library.readers",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transforms",
            fields=[
                ("transform_id", models.AutoField(primary_key=True, serialize=False)),
                ("transform_name", models.TextField()),
                (
                    "transform_kwargs",
                    models.ManyToManyField(to="config_library.kvstore"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Writers",
            fields=[
                ("writer_id", models.AutoField(primary_key=True, serialize=False)),
                ("writer_name", models.TextField()),
                ("writer_kwargs", models.ManyToManyField(to="config_library.kvstore")),
            ],
        ),
    ]
