# Generated by Django 5.0.3 on 2024-05-09 05:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConfigObjectStore",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("class_name", models.CharField(max_length=100)),
                ("json_object", models.TextField()),
                ("creation_time", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="LibraryCollection",
            fields=[("collection_name", models.CharField(max_length=100, primary_key=True, serialize=False)), ("description", models.TextField(blank=True, null=True))],
        ),
    ]
