# Generated by Django 5.0.3 on 2024-05-24 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config_library", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LibraryCollection",
        ),
    ]
